// Workspace-wide lint configuration (ADR-135) — one flat config for every
// package, mirroring the central-strictness approach of tsconfig.base.json.
import eslint from "@eslint/js";
import prettierConfig from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Never lint generated or derived output. worker-configuration.d.ts is
    // generated byte-for-byte (ADR-136); `wrangler types --check` owns it.
    ignores: [
      "**/node_modules/",
      "**/dist/",
      "**/.wrangler/",
      "apps/api/worker-configuration.d.ts",
    ],
  },

  eslint.configs.recommended,

  // Type-aware linting for all TypeScript. The projectService resolves each
  // package's own tsconfig, so rules like no-floating-promises — load-bearing
  // in a Worker, where a dropped promise is a silently lost write — see real
  // types instead of guessing.
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Underscore-prefixed parameters are deliberately unused (e.g. the
      // description argument in it.each table tests).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Config scripts (vite.config.ts, this file) sit outside every package
  // tsconfig — lint them without type information rather than maintaining a
  // separate tsconfig just for configs.
  {
    files: ["**/*.{js,mjs,cjs}", "**/vite.config.ts"],
    ...tseslint.configs.disableTypeChecked,
  },

  // Vitest's asymmetric matchers (expect.stringContaining, expect.any) and
  // mock call records are typed `any` by design; flagging every use buries
  // real findings. All other unsafe-* rules stay on in tests.
  {
    files: ["**/test/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },

  // React hooks correctness for the web app. Rules listed explicitly — the
  // plugin's bundled preset formats have shifted between majors, and these
  // two rules are the entire point of the plugin.
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Last: disable every stylistic rule Prettier owns (ADR-135 splits the
  // jobs — ESLint finds bugs, Prettier formats).
  prettierConfig,
);
