-- Migration 0001 — the ping table (Phase 0A).
--
-- ping backs the disposable /v1/ping-store route and exists to prove the
-- ADR-129 schema conventions end-to-end:
--   * STRICT table
--   * application-generated UUIDv7 id stored as TEXT
--   * UTC Unix-millisecond timestamps stored as INTEGER
-- The table and its route are removed when Phase 0A is signed off
-- (PHASE-0A-BRIEF.md, scope item 3). Migrations are numbered and
-- forward-only (ARCHITECTURE.md §4.0) — never edit an applied migration.

CREATE TABLE ping (
  id TEXT PRIMARY KEY,          -- UUIDv7, generated by the API (ADR-129)
  subject TEXT NOT NULL UNIQUE, -- JWT subject owning this row; the upsert key
  value TEXT NOT NULL,
  created_at INTEGER NOT NULL,  -- Unix milliseconds, UTC
  updated_at INTEGER NOT NULL   -- Unix milliseconds, UTC
) STRICT;
